### ISSUE TITLE
Route issue

### ISSUE THREAD

**Issue by tatobox** [gis-ops/valhalla-app#216]
### What is the problem you are facing
When I create a walking route the track goes on the road and does not follow the sidewalk
Starting point: 44.49690 11.32582.
End point: 44.49774 11.32719

### What is your suggested solution
It follows thesidewalk  as marked in blue in the photo.

### Screenshots

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/gis-ops/valhalla-app/assets/153958793/c6160e35-a3cb-4da6-8792-dfed2d082486)"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/gis-ops/valhalla-app/assets/153958793/def055da-391c-4f0d-b0db-4c4371036d8c)"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nilsnolde** [comment]
then it's more likely that the sidewalks are not properly connected with the road I think. that probably happens a lot, unfortunately it becomes a huge mess when adding sidewalks as separate geometries (which has become kinda the default in osm, great for wheelchair stuff, but I know lots of big mappers hate it because of exactly this, the maintenance hassle).

in any case, this is an issue for https://github.com/valhalla/valhalla. best to include a link to https://valhalla.openstreetmap.de/ with that route to make things easy for us.

**Comment by tatobox** [comment]
Thanks and sorry if I'm in the wrong place.
I opened issue #4657 on girhub.com/valhalla/valhalla
