### ISSUE TITLE
Map always points to "Berlin" location when app first starts.

### ISSUE THREAD

**Issue by inceptionabhishek** [gis-ops/valhalla-app#85]
I think it should point to where the user is currently accessing the map. As a user, I expect it to auto-locate me and only open the map in that area. We always need to point it at some particular region or place why not where we currently at instead of some random location from the world for this instance "Berlin". 

For example, I am from India so as a user I would like it to open an Indian location when the app first starts like(google maps), but it always points to berlin.

I am attaching the screenshot for this issue, please have a look at it :
<img width="949" alt="image" src="https://user-images.githubusercontent.com/65409282/222936368-bcb829aa-104b-43b0-a1de-c1bf8976f314.png">

I know how to resolve this issue, and I would like to work on this if you approve. _**please assign me this.**_ @nilsnolde

**Comment by nilsnolde** [comment]
There's another issue that will remember the last map extent in the local storage: #50. Once that's solved, it will only default to Berlin once someone opens the app in the current browser for the first time. 

I prefer solving that issue instead of asking for the user's location, it's always a bit dodgy (e.g. Google Maps). But if there's enough user interest, we could add it. Hasn't been raised in the 1.5 years this web app exists, OSM-affine people are commonly also very privacy-focused.
